"""remove the password that use to store hash password

Revision ID: 48f8a0eb30ba
Revises: ce3e1aabe2ab
Create Date: 2026-08-15 10:57:12.229416

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '48f8a0eb30ba'
down_revision: str | Sequence[str] | None = 'ce3e1aabe2ab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
