"""update user_id to nullble and add email to otp code table

Revision ID: 7c70eda45fbb
Revises: 3047da0a2fbb
Create Date: 2026-10-09 12:20:36.040121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c70eda45fbb'
down_revision: Union[str, Sequence[str], None] = '3047da0a2fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('email', sa.Text(), nullable=False))
    op.alter_column('otp_codes', 'user_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_otp_codes_email'), 'otp_codes', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_codes_email'), table_name='otp_codes')
    op.alter_column('otp_codes', 'user_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('otp_codes', 'email')
    # ### end Alembic commands ###
