"""make access_token_enc nullable

Revision ID: f148db28bf92
Revises: ae37df5918ac
Create Date: 2026-08-15 21:40:33.518553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f148db28bf92'
down_revision: Union[str, Sequence[str], None] = 'ae37df5918ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth_identities', 'access_token_enc',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth_identities', 'access_token_enc',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
