class SessionNotFoundError(Exception): ...

class SessionRevokedError(Exception): ...

class SessionExpiredError(Exception): ...

class UserNotFoundError(Exception): ...

class OAuthIdentityAlreadyLinkedError(Exception): ...

class CodeNotFoundError(Exception): ...

class CodeExpiredError(Exception): ...

class CodeConsumedError(Exception): ...

class CodeLockedError(Exception): ...